-- =====================================================================
-- Havenwear Care — core schema
--
-- Lives inside the Hisab Kitab Supabase project so that the Shopify orders,
-- customers and courier tracking it already syncs are reused, never copied.
-- Everything here is additive and prefixed `crm_`; Hisab Kitab tables are
-- only READ (through security-definer functions that expose support-relevant
-- columns — never costs, settlements or other finance data).
--
-- Access model: a signed-in user has CRM access only when they have an
-- active row in crm_members (viewer < agent < admin). Hisab Kitab roles are
-- unrelated, so CRM users get no finance access and vice versa.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Types
-- ---------------------------------------------------------------------
create type public.crm_role as enum ('viewer', 'agent', 'admin');
create type public.crm_status as enum ('open', 'in_progress', 'awaiting_customer', 'resolved');
create type public.crm_severity as enum ('non_serious', 'serious');
create type public.crm_channel as enum ('whatsapp', 'call', 'instagram', 'facebook', 'email', 'website', 'other');
create type public.crm_resolution as enum (
  'exchange', 'refund', 'partial_refund', 'reship', 'voucher', 'return_accepted',
  'info_provided', 'courier_claim', 'no_action', 'no_response'
);
create type public.crm_customer_flag as enum ('none', 'vip', 'watch', 'blocked');

-- ---------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------

-- Pakistani phone numbers arrive as 0300…, +92300…, 0092300…, 300…, with
-- dashes/spaces. One canonical key (92XXXXXXXXXX) identifies a customer.
create or replace function public.crm_phone_key(p text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select case
    when d = '' then null
    when d ~ '^0092' then substr(d, 3)
    when d ~ '^92[0-9]{10}$' then d
    when d ~ '^0[0-9]{10}$' then '92' || substr(d, 2)
    when d ~ '^3[0-9]{9}$' then '92' || d
    else d
  end
  from (select regexp_replace(coalesce(p, ''), '[^0-9]', '', 'g') as d) x;
$$;

-- Members -------------------------------------------------------------
create table public.crm_members (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  full_name text,
  role public.crm_role not null default 'agent',
  active boolean not null default true,
  auto_assign boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.crm_my_role()
returns public.crm_role
language sql
stable
security definer
set search_path = ''
as $$
  select role from public.crm_members where user_id = (select auth.uid()) and active;
$$;

create or replace function public.crm_has(min_role public.crm_role)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.crm_my_role() >= min_role, false);
$$;

create or replace function public.crm_assert(min_role public.crm_role)
returns void
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.crm_has(min_role) then
    raise exception 'Not allowed' using errcode = '42501';
  end if;
end;
$$;

-- Settings ------------------------------------------------------------
create table public.crm_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid()
);

insert into public.crm_settings (key, value) values
  ('auto_assign', 'true'),
  ('auto_close_awaiting_days', '7'),
  ('order_prefix', '"#haven"'),
  ('brand_name', '"Havenwear"'),
  ('store_url', '"https://havenwearpakistan.com"'),
  ('watch', '{"booked_days": 3, "in_transit_days": 5}'),
  ('tracking_urls', '{"postex": "https://postex.pk/tracking?cn={tracking}", "xps": "", "tranzo": "", "blueex": "", "mnp": ""}');

create or replace function public.crm_setting(p_key text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select value from public.crm_settings where key = p_key;
$$;

-- Complaint types -----------------------------------------------------
create table public.crm_complaint_types (
  id smallint generated by default as identity primary key,
  label text not null unique check (length(label) between 1 and 60),
  category text not null default 'product' check (category in ('delivery', 'product', 'service', 'other')),
  default_severity public.crm_severity not null default 'non_serious',
  sla_hours int not null default 48 check (sla_hours between 1 and 720),
  follow_up_days int not null default 2 check (follow_up_days between 0 and 60),
  keywords text[] not null default '{}',
  sort smallint not null default 100,
  active boolean not null default true
);

-- The 13 types from the original Google Sheet, plus SLA/severity defaults and
-- English + Roman Urdu keywords used to auto-suggest the type from the message.
insert into public.crm_complaint_types (label, category, default_severity, sla_hours, follow_up_days, sort, keywords) values
  ('Late delivery', 'delivery', 'non_serious', 24, 1, 10,
    array['late','delay','not received','not delivered','where is my order','still waiting','nahi mila','nhi mila','abhi tak','kab milega','kab aye','kab ayega','intezar','order kahan','parcel kahan']),
  ('Fabric not liked', 'product', 'non_serious', 48, 2, 20,
    array['fabric','kapra','kapda','material','thin','patla','rough','cheap quality','quality achi nahi','garmi']),
  ('Design not liked', 'product', 'non_serious', 48, 2, 30,
    array['design','pasand nahi','not like','dont like','don''t like','achi nahi lagi','style']),
  ('Size / fit issue', 'product', 'non_serious', 48, 2, 40,
    array['size','fit','chota','choti','bara','bari','small','large','tight','loose','tang','khula','length','lambi','short']),
  ('Wrong item / color / size', 'product', 'serious', 24, 1, 50,
    array['wrong','galat','ghalat','different item','dusra','doosra','wrong size','wrong color','wrong colour','not what i ordered','kuch aur']),
  ('Damaged / defective item', 'product', 'serious', 24, 1, 60,
    array['damaged','damage','defect','torn','phata','phati','phat','hole','surakh','stain','daagh','dagh','kharab','broken','stitching','silai','ganda','used']),
  ('Print quality issue', 'product', 'serious', 48, 2, 70,
    array['print','fade','faded','crack','peel','utar','utar gaya','nikal','blur']),
  ('Color differs from photos', 'product', 'non_serious', 48, 2, 80,
    array['colour','color','rang','shade','different from picture','tasveer','picture','photo mein','pic']),
  ('Missing item', 'delivery', 'serious', 24, 1, 90,
    array['missing','kam','less item','only one','aik hi','ek hi','not in parcel','incomplete','pura nahi']),
  ('Courier behavior', 'delivery', 'non_serious', 48, 2, 100,
    array['rider','courier','rude','badtameez','misbehave','fake attempt','call nahi','refused to wait','extra charges','paise zyada']),
  ('Exchange delay', 'service', 'serious', 24, 1, 110,
    array['exchange','replace','replacement','badal','badalna','tabdeel','swap']),
  ('Support experience', 'service', 'non_serious', 24, 1, 120,
    array['no reply','reply nahi','jawab nahi','response','ignore','seen','support','customer service']),
  ('Other', 'other', 'non_serious', 48, 2, 999, '{}');

-- Cases ---------------------------------------------------------------
create table public.crm_cases (
  id bigint generated always as identity primary key,
  ref text generated always as ('HC-' || lpad(id::text, 5, '0')) stored,
  received_at timestamptz not null default now(),
  channel public.crm_channel not null default 'whatsapp',
  -- Shopify order (Hisab Kitab public.orders.id) + snapshot of who/what
  order_id bigint,
  order_name text check (length(order_name) <= 40),
  customer_name text check (length(customer_name) <= 120),
  phone text check (length(phone) <= 40),
  phone_key text generated always as (public.crm_phone_key(phone)) stored,
  city text check (length(city) <= 80),
  items jsonb not null default '[]' check (jsonb_typeof(items) = 'array' and pg_column_size(items) < 8000),
  courier text check (length(courier) <= 30),
  tracking_number text check (length(tracking_number) <= 40),
  -- Complaint
  type_id smallint references public.crm_complaint_types (id),
  severity public.crm_severity not null,
  status public.crm_status not null default 'open',
  description text not null check (length(description) between 1 and 5000),
  tags text[] not null default '{}',
  -- Workflow
  assignee uuid references public.crm_members (user_id) on delete set null,
  follow_up_at timestamptz,
  due_at timestamptz,
  first_response_at timestamptz,
  resolved_at timestamptz,
  resolution public.crm_resolution,
  resolution_cost numeric(12, 2) not null default 0 check (resolution_cost >= 0),
  resolution_notes text check (length(resolution_notes) <= 5000),
  last_activity_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crm_cases_resolved_consistency check ((status = 'resolved') = (resolved_at is not null))
);

create index crm_cases_status_due_idx on public.crm_cases (status, due_at);
create index crm_cases_assignee_idx on public.crm_cases (assignee, status);
create index crm_cases_received_idx on public.crm_cases (received_at desc, id desc);
create index crm_cases_phone_idx on public.crm_cases (phone_key);
create index crm_cases_order_idx on public.crm_cases (order_id);
create index crm_cases_order_name_idx on public.crm_cases (lower(order_name));
create index crm_cases_tracking_idx on public.crm_cases (tracking_number);
create index crm_cases_type_idx on public.crm_cases (type_id);
create index crm_cases_followup_idx on public.crm_cases (follow_up_at) where status <> 'resolved';
create index crm_cases_name_trgm on public.crm_cases using gin (customer_name extensions.gin_trgm_ops);

-- Timeline ------------------------------------------------------------
create table public.crm_case_events (
  id bigint generated always as identity primary key,
  case_id bigint not null references public.crm_cases (id) on delete cascade,
  kind text not null check (kind in (
    'created', 'status', 'assigned', 'note', 'contact', 'follow_up', 'resolved', 'reopened', 'attachment', 'system', 'edit'
  )),
  body text check (length(body) <= 5000),
  meta jsonb not null default '{}',
  actor uuid default auth.uid(),
  created_at timestamptz not null default now()
);
create index crm_case_events_case_idx on public.crm_case_events (case_id, created_at);
create index crm_case_events_actor_idx on public.crm_case_events (actor);

-- Attachments (photos the customer sends — compressed in the browser) ---
create table public.crm_attachments (
  id bigint generated always as identity primary key,
  case_id bigint not null references public.crm_cases (id) on delete cascade,
  path text not null unique check (path ~ '^cases/[0-9]+/[A-Za-z0-9._-]+$'),
  mime text not null check (mime in ('image/webp', 'image/jpeg', 'image/png')),
  size_bytes int not null check (size_bytes between 1 and 3000000),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);
create index crm_attachments_case_idx on public.crm_attachments (case_id);

-- Customer profile: only what the team adds (flag / tags / note). Order
-- history and stats are computed from Hisab Kitab's orders, not copied.
create table public.crm_customer_profiles (
  phone_key text primary key check (length(phone_key) between 6 and 20),
  flag public.crm_customer_flag not null default 'none',
  tags text[] not null default '{}',
  note text check (length(note) <= 2000),
  updated_by uuid default auth.uid(),
  updated_at timestamptz not null default now()
);

-- WhatsApp / reply templates -----------------------------------------
create table public.crm_templates (
  id smallint generated by default as identity primary key,
  title text not null check (length(title) between 1 and 60),
  body text not null check (length(body) between 1 and 2000),
  category text not null default 'general' check (category in ('general', 'delivery', 'resolution', 'followup', 'info')),
  sets_status public.crm_status,
  sort smallint not null default 100,
  active boolean not null default true
);

insert into public.crm_templates (title, category, sets_status, sort, body) values
  ('Acknowledge complaint', 'general', 'in_progress', 10,
   E'Assalam o Alaikum {first_name}! {brand} support here. We have received your concern about order {order} (ref {ref}). Hum isay jald az jald resolve karenge, InshaAllah.'),
  ('Ask for photos', 'info', 'awaiting_customer', 20,
   E'Hi {first_name}, sorry for the inconvenience. Please share clear pictures of the item (front, back and the issue) along with the parcel/label so we can resolve order {order} quickly.'),
  ('Order tracking update', 'delivery', null, 30,
   E'Hi {first_name}, your order {order} is with {courier}. Tracking number: {tracking}\n{tracking_url}\nCurrent status: {shipment_status}.'),
  ('Delivery attempt failed', 'delivery', null, 40,
   E'Assalam o Alaikum {first_name}, {courier} rider tried to deliver your {brand} order {order} but could not reach you. Please confirm your address and a suitable time so we can re-attempt delivery. Shukriya!'),
  ('Confirm address', 'delivery', 'awaiting_customer', 50,
   E'Hi {first_name}, please confirm your complete address with nearest landmark and an active number for order {order}. Rider will contact you before delivery.'),
  ('Exchange approved', 'resolution', 'in_progress', 60,
   E'Good news {first_name}! Your exchange for order {order} is approved. Please keep the item unused with tags; our courier will collect it and deliver the replacement.'),
  ('Refund processed', 'resolution', null, 70,
   E'Hi {first_name}, your refund for order {order} has been processed. It may take 3–5 working days to reflect. Sorry again for the trouble.'),
  ('Follow-up', 'followup', null, 80,
   E'Hi {first_name}, just following up on your concern (ref {ref}) for order {order}. Kya aap ka masla hal ho gaya? Let us know if you need anything else.'),
  ('Resolved — thank you', 'resolution', null, 90,
   E'Thank you {first_name} for your patience! Your concern for order {order} is now resolved. We hope to serve you again at {brand} ❤️');

-- Delivery watch: proactive outreach log (one row per shipment) --------
create table public.crm_delivery_contacts (
  shipment_id bigint primary key,
  outcome text not null check (outcome in ('reached', 'no_answer', 'address_updated', 'will_receive', 'refused', 'cancel_requested', 'dismissed')),
  note text check (length(note) <= 1000),
  attempts int not null default 1,
  status_at_contact text,
  contacted_by uuid default auth.uid(),
  contacted_at timestamptz not null default now()
);

-- Hisab Kitab orders: index the canonical phone so customer lookups are instant.
create index if not exists crm_orders_phone_key_idx on public.orders (public.crm_phone_key(phone));

-- ---------------------------------------------------------------------
-- Automation triggers
-- ---------------------------------------------------------------------

create or replace function public.crm_norm_order(p text)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  prefix text := coalesce(public.crm_setting('order_prefix') #>> '{}', '#');
  v text := lower(regexp_replace(coalesce(p, ''), '\s+', '', 'g'));
  digits text;
begin
  if v = '' then return null; end if;
  digits := substring(v from '([0-9]{3,})$');
  if digits is null then return v; end if;
  return lower(prefix) || digits;
end;
$$;

-- BEFORE INSERT: fill everything that can be derived so agents type less.
create or replace function public.crm_cases_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  t public.crm_complaint_types%rowtype;
  o record;
  s record;
  prior int;
  prof public.crm_customer_profiles%rowtype;
begin
  new.order_name := public.crm_norm_order(new.order_name);

  -- Link the Shopify order and fill customer + shipment details from it
  if new.order_id is null and new.order_name is not null then
    select id into new.order_id from public.orders where lower(name) = new.order_name limit 1;
  end if;
  if new.order_id is not null then
    select name, customer_name, phone, city into o from public.orders where id = new.order_id;
    if found then
      new.order_name := coalesce(new.order_name, lower(o.name));
      new.customer_name := coalesce(nullif(trim(new.customer_name), ''), o.customer_name);
      new.phone := coalesce(nullif(trim(new.phone), ''), o.phone);
      new.city := coalesce(nullif(trim(new.city), ''), o.city);
    end if;
    if new.tracking_number is null then
      select tracking_number, courier into s from public.shipments
       where order_id = new.order_id order by created_at desc limit 1;
      if found then
        new.tracking_number := s.tracking_number;
        new.courier := coalesce(new.courier, s.courier);
      end if;
    end if;
  end if;

  if new.type_id is null then
    select id into new.type_id from public.crm_complaint_types where label = 'Other';
  end if;
  select * into t from public.crm_complaint_types where id = new.type_id;

  new.severity := coalesce(new.severity, t.default_severity, 'non_serious');
  new.due_at := coalesce(new.due_at, new.received_at + make_interval(hours => coalesce(t.sla_hours, 48)));
  if new.status <> 'resolved' then
    new.follow_up_at := coalesce(new.follow_up_at, now() + make_interval(days => coalesce(t.follow_up_days, 2)));
  end if;
  if new.status = 'resolved' and new.resolved_at is null then
    new.resolved_at := now();
  end if;

  -- Customer context tags
  if new.phone is not null then
    select count(*) into prior from public.crm_cases
     where phone_key = public.crm_phone_key(new.phone) and received_at > new.received_at - interval '90 days';
    if prior >= 1 and not 'repeat' = any (new.tags) then
      new.tags := array_append(new.tags, 'repeat');
    end if;
    select * into prof from public.crm_customer_profiles where phone_key = public.crm_phone_key(new.phone);
    if found and prof.flag = 'vip' and not 'vip' = any (new.tags) then
      new.tags := array_append(new.tags, 'vip');
      -- VIPs get a tighter SLA (half)
      new.due_at := new.received_at + make_interval(hours => greatest(1, coalesce(t.sla_hours, 48) / 2));
    end if;
  end if;

  -- Auto-assign to the least-loaded active agent
  if new.assignee is null and new.status <> 'resolved' and coalesce((public.crm_setting('auto_assign'))::boolean, true) then
    select m.user_id into new.assignee
      from public.crm_members m
      left join public.crm_cases c on c.assignee = m.user_id and c.status <> 'resolved'
     where m.active and m.auto_assign and m.role >= 'agent'
     group by m.user_id
     order by count(c.id), random()
     limit 1;
  end if;

  new.last_activity_at := now();
  return new;
end;
$$;

create trigger crm_cases_before_insert
  before insert on public.crm_cases
  for each row execute function public.crm_cases_before_insert();

create or replace function public.crm_cases_before_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  t public.crm_complaint_types%rowtype;
begin
  new.updated_at := now();
  -- Identity columns are immutable
  new.created_by := old.created_by;
  new.created_at := old.created_at;

  if new.order_name is distinct from old.order_name then
    new.order_name := public.crm_norm_order(new.order_name);
  end if;

  if new.status = 'resolved' and old.status <> 'resolved' then
    new.resolved_at := coalesce(new.resolved_at, now());
    new.follow_up_at := null;
  elsif new.status <> 'resolved' and old.status = 'resolved' then
    new.resolved_at := null;
    new.resolution := null;
    select * into t from public.crm_complaint_types where id = new.type_id;
    new.follow_up_at := coalesce(new.follow_up_at, now() + make_interval(days => coalesce(t.follow_up_days, 1)));
    new.due_at := now() + make_interval(hours => coalesce(t.sla_hours, 24));
  elsif new.status <> 'resolved' then
    new.resolved_at := null;
  end if;

  if new.type_id is distinct from old.type_id and new.due_at is not distinct from old.due_at then
    select * into t from public.crm_complaint_types where id = new.type_id;
    new.due_at := new.received_at + make_interval(hours => coalesce(t.sla_hours, 48));
  end if;
  return new;
end;
$$;

create trigger crm_cases_before_update
  before update on public.crm_cases
  for each row execute function public.crm_cases_before_update();

-- AFTER triggers write the timeline, so the client never double-writes history.
create or replace function public.crm_cases_after_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
begin
  if tg_op = 'INSERT' then
    insert into public.crm_case_events (case_id, kind, body, meta, actor)
    values (new.id, 'created', null, jsonb_build_object('channel', new.channel, 'assignee', new.assignee), actor);
    return new;
  end if;

  if new.status is distinct from old.status then
    if new.status = 'resolved' then
      insert into public.crm_case_events (case_id, kind, body, meta, actor)
      values (new.id, 'resolved', new.resolution_notes,
              jsonb_build_object('from', old.status, 'resolution', new.resolution, 'cost', new.resolution_cost), actor);
    elsif old.status = 'resolved' then
      insert into public.crm_case_events (case_id, kind, meta, actor)
      values (new.id, 'reopened', jsonb_build_object('to', new.status), actor);
    else
      insert into public.crm_case_events (case_id, kind, meta, actor)
      values (new.id, 'status', jsonb_build_object('from', old.status, 'to', new.status), actor);
    end if;
  end if;
  if new.assignee is distinct from old.assignee then
    insert into public.crm_case_events (case_id, kind, meta, actor)
    values (new.id, 'assigned', jsonb_build_object('from', old.assignee, 'to', new.assignee), actor);
  end if;
  if new.follow_up_at is distinct from old.follow_up_at and new.follow_up_at is not null and new.status <> 'resolved' then
    insert into public.crm_case_events (case_id, kind, meta, actor)
    values (new.id, 'follow_up', jsonb_build_object('at', new.follow_up_at), actor);
  end if;
  if new.type_id is distinct from old.type_id or new.severity is distinct from old.severity then
    insert into public.crm_case_events (case_id, kind, meta, actor)
    values (new.id, 'edit', jsonb_build_object(
      'type_from', old.type_id, 'type_to', new.type_id, 'severity_from', old.severity, 'severity_to', new.severity), actor);
  end if;
  return new;
end;
$$;

create trigger crm_cases_after_insert
  after insert on public.crm_cases
  for each row execute function public.crm_cases_after_change();

create trigger crm_cases_after_update
  after update of status, assignee, follow_up_at, type_id, severity on public.crm_cases
  for each row execute function public.crm_cases_after_change();

-- Events keep the case fresh: activity time, first response, and a customer
-- reply automatically moves an "awaiting customer" case back into progress.
create or replace function public.crm_events_after_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.kind in ('note', 'contact', 'attachment') then
    update public.crm_cases c set
      last_activity_at = now(),
      first_response_at = case
        when c.first_response_at is null and new.kind = 'contact' and coalesce(new.meta ->> 'direction', 'out') = 'out'
        then new.created_at else c.first_response_at end,
      status = case
        when new.kind = 'contact' and new.meta ->> 'direction' = 'in' and c.status = 'awaiting_customer' then 'in_progress'::public.crm_status
        when new.kind = 'contact' and coalesce(new.meta ->> 'direction', 'out') = 'out' and c.status = 'open' then 'in_progress'::public.crm_status
        else c.status end
    where c.id = new.case_id;
  end if;
  return new;
end;
$$;

create trigger crm_events_after_insert
  after insert on public.crm_case_events
  for each row execute function public.crm_events_after_insert();

create or replace function public.crm_touch_profile()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  new.updated_by := (select auth.uid());
  return new;
end;
$$;

create trigger crm_customer_profiles_touch
  before insert or update on public.crm_customer_profiles
  for each row execute function public.crm_touch_profile();

create trigger crm_settings_touch
  before insert or update on public.crm_settings
  for each row execute function public.crm_touch_profile();

-- Members may not lock themselves out or self-promote.
create or replace function public.crm_guard_member()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null then return coalesce(new, old); end if;
  if tg_op = 'DELETE' then
    if old.user_id = (select auth.uid()) then
      raise exception 'You cannot remove yourself' using errcode = '42501';
    end if;
    return old;
  end if;
  if old.user_id = (select auth.uid()) and (new.role is distinct from old.role or new.active is distinct from old.active) then
    raise exception 'You cannot change your own role or access' using errcode = '42501';
  end if;
  new.user_id := old.user_id;
  return new;
end;
$$;

create trigger crm_members_guard
  before update or delete on public.crm_members
  for each row execute function public.crm_guard_member();

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------
alter table public.crm_members enable row level security;
alter table public.crm_settings enable row level security;
alter table public.crm_complaint_types enable row level security;
alter table public.crm_cases enable row level security;
alter table public.crm_case_events enable row level security;
alter table public.crm_attachments enable row level security;
alter table public.crm_customer_profiles enable row level security;
alter table public.crm_templates enable row level security;
alter table public.crm_delivery_contacts enable row level security;

-- Read: any active member
create policy "members read" on public.crm_members for select to authenticated using ((select public.crm_has('viewer')));
create policy "members read" on public.crm_settings for select to authenticated using ((select public.crm_has('viewer')));
create policy "members read" on public.crm_complaint_types for select to authenticated using ((select public.crm_has('viewer')));
create policy "members read" on public.crm_cases for select to authenticated using ((select public.crm_has('viewer')));
create policy "members read" on public.crm_case_events for select to authenticated using ((select public.crm_has('viewer')));
create policy "members read" on public.crm_attachments for select to authenticated using ((select public.crm_has('viewer')));
create policy "members read" on public.crm_customer_profiles for select to authenticated using ((select public.crm_has('viewer')));
create policy "members read" on public.crm_templates for select to authenticated using ((select public.crm_has('viewer')));
create policy "members read" on public.crm_delivery_contacts for select to authenticated using ((select public.crm_has('viewer')));

-- Agents work cases
create policy "agents insert" on public.crm_cases for insert to authenticated with check ((select public.crm_has('agent')));
create policy "agents update" on public.crm_cases for update to authenticated
  using ((select public.crm_has('agent'))) with check ((select public.crm_has('agent')));
create policy "admins delete" on public.crm_cases for delete to authenticated using ((select public.crm_has('admin')));

-- Timeline: agents add notes / contacts / attachments as themselves; system kinds come from triggers only.
create policy "agents insert" on public.crm_case_events for insert to authenticated
  with check ((select public.crm_has('agent')) and actor = (select auth.uid()) and kind in ('note', 'contact', 'attachment'));
create policy "admins delete" on public.crm_case_events for delete to authenticated using ((select public.crm_has('admin')));

create policy "agents insert" on public.crm_attachments for insert to authenticated
  with check ((select public.crm_has('agent')) and created_by = (select auth.uid()));
create policy "owner or admin delete" on public.crm_attachments for delete to authenticated
  using ((select public.crm_has('admin')) or ((select public.crm_has('agent')) and created_by = (select auth.uid())));

create policy "agents insert" on public.crm_customer_profiles for insert to authenticated with check ((select public.crm_has('agent')));
create policy "agents update" on public.crm_customer_profiles for update to authenticated
  using ((select public.crm_has('agent'))) with check ((select public.crm_has('agent')));

create policy "agents insert" on public.crm_delivery_contacts for insert to authenticated with check ((select public.crm_has('agent')));
create policy "agents update" on public.crm_delivery_contacts for update to authenticated
  using ((select public.crm_has('agent'))) with check ((select public.crm_has('agent')));

-- Admins configure
create policy "admins write" on public.crm_complaint_types for all to authenticated
  using ((select public.crm_has('admin'))) with check ((select public.crm_has('admin')));
create policy "admins write" on public.crm_templates for all to authenticated
  using ((select public.crm_has('admin'))) with check ((select public.crm_has('admin')));
create policy "admins update" on public.crm_settings for update to authenticated
  using ((select public.crm_has('admin'))) with check ((select public.crm_has('admin')));
create policy "admins update" on public.crm_members for update to authenticated
  using ((select public.crm_has('admin'))) with check ((select public.crm_has('admin')));
create policy "admins delete" on public.crm_members for delete to authenticated using ((select public.crm_has('admin')));
-- New members are created by the crm-admin edge function (service role).

-- Privileges: Hisab Kitab revokes defaults, so grant exactly what is needed.
revoke all on public.crm_members, public.crm_settings, public.crm_complaint_types, public.crm_cases,
  public.crm_case_events, public.crm_attachments, public.crm_customer_profiles, public.crm_templates,
  public.crm_delivery_contacts from anon, public;
grant select, update, delete on public.crm_members to authenticated;
grant select, update on public.crm_settings to authenticated;
grant select, insert, update, delete on public.crm_complaint_types, public.crm_templates to authenticated;
grant select, insert, update, delete on public.crm_cases to authenticated;
grant select, insert, delete on public.crm_case_events, public.crm_attachments to authenticated;
grant select, insert, update on public.crm_customer_profiles, public.crm_delivery_contacts to authenticated;
grant all on public.crm_members, public.crm_settings, public.crm_complaint_types, public.crm_cases,
  public.crm_case_events, public.crm_attachments, public.crm_customer_profiles, public.crm_templates,
  public.crm_delivery_contacts to service_role;

-- ---------------------------------------------------------------------
-- Storage: private bucket for complaint photos
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('crm-attachments', 'crm-attachments', false, 3000000, array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do nothing;

create policy "crm members read attachments" on storage.objects for select to authenticated
  using (bucket_id = 'crm-attachments' and (select public.crm_has('viewer')));
create policy "crm agents upload attachments" on storage.objects for insert to authenticated
  with check (bucket_id = 'crm-attachments' and (select public.crm_has('agent')) and name ~ '^cases/[0-9]+/[A-Za-z0-9._-]+$');
create policy "crm owner or admin delete attachments" on storage.objects for delete to authenticated
  using (bucket_id = 'crm-attachments' and ((select public.crm_has('admin')) or owner_id = (select auth.uid())::text));
